# Generated by Django 3.0.1 on 2020-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('link_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recordes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
